### ISSUE TITLE
Install Docs Reference Nonexistent File

### ISSUE THREAD

**Issue by fdamstra** [HubbleStack/Hubble#1]
The installation instructions (https://hubblestack.readthedocs.org/en/latest/chapters/installation.html) have you clone hubble, and then instruct you to copy hubble.py. This module isn't included in the hubble package, though it appears to be in nova.

**Comment by cedwards** [comment]
I will address the docs today. Thanks for pointing this out.

**Comment by cedwards** [comment]
I've updated the docs to refer to Nova and clarified the installation chapter a bit. Right now most of the focus is on Nova. The other components we plan to bundle as SPM packages.
