### ISSUE TITLE
Move installation-specific configuration to /etc/hubble/hubble.d

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#100]
We want to be able to control the default config without trampling user-specific configuration. This will add the ability to put user-specific config in a subdirectory (`/etc/hubble/hubble.d/`) and merge with our shipped config. We will also make the shipped config *not* a config file as far as rpm/deb are concerned, so updates we ship will overwrite what we've shipped previously.

**Comment by basepi** [comment]
https://jira.corp.adobe.com/browse/CSTTEAM-41402

**Comment by basepi** [comment]
https://github.com/hubblestack/hubble/pull/123

**Comment by fossam** [comment]
I anticipate questions regarding to the order the user defined configuration files are loaded and which settings get used when there's overlap.

**Comment by basepi** [comment]
I honestly don't. Because for 99% of teams, it's going to be just moving their returner config to a separate file, no other changes necessary. So while you can add multiple files and start worrying about their order, it's going to be just one file in practice and the order is (1) /etc/hubble/hubble (2) their custom config, which will overwrite any keys in our main config.

I did add support for `user_schedule` so if we have user-specific scheduled jobs they could add that key to their user config and it wouldn't overwrite our schedule, but rather would be merged by the scheduler itself.
