### ISSUE TITLE
awk module for nova

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#109]
From #108:

> similar to grep, but allows more flexible text processing capabilities. GNU awk has "--sandbox" feature that would disable an obvious way to issue arbitrary system commands.

**Comment by fossam** [comment]
I think lines following and including `salt.modules.augeas_cfg` should be removed as those have nothing to do with the awk module. It's a description of an idea for a different module.

**Comment by basepi** [comment]
Whoops, you're right, copy-pasta. Removed.

**Comment by basepi** [comment]
Solved by FDG
