### ISSUE TITLE
Nebula module for gathering checksums

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#111]
Would be useful to be able to gather a checksum for a specific file across all hosts to check for known bad binaries, etc.

**Comment by mew1033** [comment]
This can be done with osquery. Something like:

    SELECT * FROM hash WHERE path='/path/to/file'

Were you thinking something osquery independent? If you added it to osquery, it would return the hash every x time (fifteen minute, hour, day).

**Comment by basepi** [comment]
Nah, that should work nicely. If we ever want to, we can add something that is longer than daily.
