### ISSUE TITLE
reflect changes to host's settings in logs and returner outputs

### ISSUE THREAD

**Issue by fossam** [hubblestack/hubble#114]
An issue so far has been that a change in host's settings (hostname, fqdn, ip address) has required Hubble restart. Changes to these settings may happen when Hubble starts before host provisioning scripts have finished, for example. As these settings change, logs need to reflect the accurate settings or tracking over time becomes impossible if no other stable identifiers are present.

The problem can be solved by doing the following - 
* re-evaluate and check if certain grains have changed over some time-interval (say, once an hour), 
* if any of those grains have changed, log loudly about it through log files and returners (say, to sourcetype=hubble_hubble) so it is possible to know the progression from grain value to another.
* assign new grain value to the grain.

**Comment by fossam** [comment]
#102 
I think these issues are related. 
Is it possible to have logging to returners in a returner agnostic manner?

**Comment by basepi** [comment]
There are two separate issues at work here. The easy one, which is grains refresh. And the hard one, which is #102.

**Comment by mew1033** [comment]
For refreshing grains, could we just use this: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.refresh_grains ?

**Comment by basepi** [comment]
Nope. That requires a full minion to be spun up. I have to generate them manually. I don't think it will be terrible.

**Comment by basepi** [comment]
Grains refresh hourly and return to splunk.
