### ISSUE TITLE
Add timeouts to osquery queries

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#130]
As far as I can tell we'll need to add a dep on the suprocess32 backport library to get the python 3.2+ version of subprocess which includes timeouts. Should be pretty straightforward. This will prevent hanging osqueryi queries from killing our daemon.

**Comment by mew1033** [comment]
As discussed previously, salt upstream has a timeout feature on cmd.run. Unfortunately, it looks like it might be broken. Is it worth trying to fix it upstream so we don't have to include a new module?

**Comment by basepi** [comment]
We'll see what kind of traction we get on that issue. And maybe I'll find some time to code dive salt and see if I can fix it. They're pretty busy over there. In any case it's not on my current sprint or anything, so we'll let it marinate.

**Comment by mew1033** [comment]
Looks like adding `use_vt=True` to the command makes the timeout feature work. Not sure what other effects it may have.
https://github.com/saltstack/salt/issues/42696

**Comment by damon-atkins** [comment]
I have dealt  with this before but not in python. the key is setid and killpg 
https://github.com/saltstack/salt/issues/42696#issuecomment-320043201

https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true  
https://stackoverflow.com/questions/2638909/killing-a-subprocess-including-its-children-from-python

**Comment by basepi** [comment]
This is done.
