### ISSUE TITLE
Shell history not populating with osquery

### ISSUE THREAD

**Issue by tsharpe** [hubblestack/hubble#136]
The query listed on line 9 of:

https://github.com/hubblestack/hubblestack_data/blob/develop/hubblestack_nebula/hubblestack_nebula_queries.yaml

```
#osqueryi --json "SELECT t.unix_time AS query_time, uid, gid, username AS user, groupname AS 'group', command, time, history_file FROM users JOIN groups USING (gid) JOIN shell_history USING (uid) LEFT JOIN time as t WHERE time > strftime('%s', 'now', '-16 minutes');"
```
```
[

]
```

Tested on CentOS 7.3, Ubuntu 16.04.3 and Debian 9.1 running osqueryi 2.6

**Comment by cedwards** [comment]
I get the same result on Debian 9, Ubuntu 17.04, CentOS 7.3 and CentOS 6.9.

```
osqueryi --json "SELECT t.unix_time AS query_time, uid, gid, username AS user, groupname AS 'group', command, time, history_file FROM users JOIN groups USING (gid) JOIN shell_history USING (uid) LEFT JOIN time as t WHERE time > strftime('%s', 'now', '-16 minutes');"
```

**Comment by fossam** [comment]
I think this only populates if timestamps are enabled in bash history, otherwise we'd pull the full history on each run and we'd not know timing of commands. 
Please enable them by defining `HISTTIMEFORMAT` environment variable.

**Comment by mew1033** [comment]
@fossam is correct. If we can come up with a better way to get bash history, I'd be all ears.
