### ISSUE TITLE
Centos6 package: broken glibc dependency

### ISSUE THREAD

**Issue by tsharpe** [hubblestack/hubble#145]
```
# service hubble start
Starting hubble
/opt/hubble/hubble: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/hubble/hubble-libs/libz.so.1
```
Default CentOS 6.9 has glibc 2.2 installed
```
Installed Packages
Name        : glibc
Arch        : x86_64
Version     : 2.12
Release     : 1.209.el6_9.2
Size        : 13 M
Repo        : installed
From repo   : updates
Summary     : The GNU libc libraries
URL         : http://sources.redhat.com/glibc/
License     : LGPLv2+ and LGPLv2+ with exceptions and GPLv2+
```
Proposed solution:
https://unix.stackexchange.com/questions/176489/how-to-update-glibc-to-2-14-in-centos-6-5

**Comment by fossam** [comment]
Thanks for testing centos 6.
I don't get the same result, though. 
In my case:
```
# rpm -qa |grep glibc
glibc-common-2.12-1.209.el6_9.2.x86_64
glibc-2.12-1.209.el6_9.2.x86_64
```
Which rpm did you use for centos 6? As of this moment rpm for centos 6 isn't uploaded yet, but the Dockerfile is available [here](https://github.com/hubblestack/hubble/pull/141/commits/df856f49d7746df1031a8e0bf6fa79bbf9700f81)
 and produces an rpm: 
```
# /opt/hubble/hubble -v grains.item osfinger
{'osfinger': 'CentOS-6'}
```

**Comment by tsharpe** [comment]
My confusion I saw
```
https://github.com/hubblestack/hubble/releases/download/v2.2.0/hubblestack-2.2.0-1.al1609.x86_64.rpm
```
and thought that was `el609` not `al609` for Amazon Linux. The install from source works fine. I will wait for the `el609` rpm build or build it myself
