### ISSUE TITLE
CIS-5.2.12 missing from centos-7-level-1-scored-v2-1-0.yaml

### ISSUE THREAD

**Issue by whackyhack** [hubblestack/hubble#155]
Even though it is in centos-6-level-1-scored-v2-0-1.yaml as well as in centos-7-level-1-scored-v2-0-0.yaml.  Checked CIS benchmark v2.1.0 and v2.1.1, 5.2.12 is present.

**Comment by basepi** [comment]
Thanks for the report.

**Comment by whackyhack** [comment]
Pull request 50 added

**Comment by whackyhack** [comment]
PR 56 merged in hubblestack_data fixes this
