### ISSUE TITLE
Incorrect tag for CIS-5.2.5 in several CentOS yaml files

### ISSUE THREAD

**Issue by whackyhack** [hubblestack/hubble#159]
As mentioned while attempting #82, I notice that the same entry (sshd_max_auth_retries) is identified differently from 5.2.5 in some files.  So I verified that CIS benchmark for CentOS 6 and that for CentOS 7 both identify this as 5.2.5, not 6.2.5.

To discover which ones have this problem, I display this section in every centos file:
```
$ for file in centos-*; do echo $file ----; sed -n '/sshd_max_auth_retries/,/description/p' $file; done
centos-6-level-1-scored-v1-0-0.yaml ----
    sshd_max_auth_retries:
      data:
        'CentOS-6':
          - '/etc/ssh/sshd_config':
              tag: 'CIS-6.2.5'
              pattern: "^MaxAuthTries"
              match_output: "MaxAuthTries 4"
      description: 'Set SSH MaxAuthTries to 4 or Less'
centos-6-level-1-scored-v2-0-1.yaml ----
    sshd_max_auth_retries:
      data:
        'CentOS-6':
          - '/etc/ssh/sshd_config':
              tag: CIS-5.2.5
              pattern: "^MaxAuthTries"
              match_output: "MaxAuthTries 4"
      description: Ensure SSH MaxAuthTries is set to 4 or less
centos-7-level-1-scored-v1-0-0.yaml ----
    sshd_max_auth_retries:
      data:
        CentOS Linux-7:
        - /etc/ssh/sshd_config:
            match_output: MaxAuthTries 4
            pattern: ^MaxAuthTries
            tag: CIS-6.2.5
      description: Set SSH MaxAuthTries to 4 or Less
centos-7-level-1-scored-v2-0-0.yaml ----
    sshd_max_auth_retries:
      data:
        CentOS Linux-7:
        - /etc/ssh/sshd_config:
            match_output: MaxAuthTries 4
            pattern: ^MaxAuthTries
            tag: CIS-5.2.5
      description: Ensure SSH MaxAuthTries is set to 4 or less
centos-7-level-1-scored-v2-1-0.yaml ----
    sshd_max_auth_retries:
      data:
        CentOS Linux-7:
        - /etc/ssh/sshd_config:
            match_output: "^MaxAuthTries +[1-4]$"
            match_output_regex: True
            pattern: ^MaxAuthTries
            tag: CIS-5.2.5
      description: Ensure SSH MaxAuthTries is set to 4 or less
```

So centos-7-level-1-scored-v1-0-0.yaml and centos-6-level-1-scored-v1-0-0.yaml are incorrect.

**Comment by whackyhack** [comment]
By checking only my downloaded benchmark versions, I gave CIS too much credit.  The yaml files are correct when compared with matching benchmark versions.

**Comment by basepi** [comment]
Yep. For a standards body, they're not very good at standardizing....

It's actually been one of the most infuriating things when developing hubble.

**Comment by mew1033** [comment]
That's why each of the nova profiles has to be pegged to a specific version of the CIS check. So for example `centos-7-level-1-scored-v2-1-0.yaml` should match the CIS pdf for CentOS 7, version 2.1.0, published on 06-02-2016. Not only do they overhaul the numbers between OSes, but even between major versions of the same OS.

Sigh...
