### ISSUE TITLE
File system options should be checked with mount or like

### ISSUE THREAD

**Issue by whackyhack** [hubblestack/hubble#165]
Presently most if not all file system options (e.g., CIS-1.1.15 for CentOS 7 v2.1.0, /dev/shm nodev) are implemented with grep fstab.  This can produce false positives with file systems such as /dev/shm that uboot creates before ever coming to /etc/fstab; just as well, this can easily be spoofed to produce false negatives when a system is compromised.

Proper implementation should use "command" module with mount or the like.  In fact, CIS benchmark uses mount.

**Comment by whackyhack** [comment]
Just saw that "command" module was deprecated.  Is there a replacement so 'mount' output can be examined?

**Comment by basepi** [comment]
Our solution has been to use `misc.py` where you can code specific checks without the risk of being able to do arbitrary command execution through hubblestack_data.

**Comment by fossam** [comment]
@whackyhack  Would _/proc/mounts_ be an good source?

**Comment by whackyhack** [comment]
@fossam Bingo!  This will not work for every OS but as far as Linux goes, this is excellent.  Thanks for shedding the light.

**Comment by whackyhack** [comment]
PR 58 merged in hubblestack_data fixes this issue.
