### ISSUE TITLE
Disable spurious FS' should be blacklist, implemented with lsmod or the like

### ISSUE THREAD

**Issue by whackyhack** [hubblestack/hubble#171]
Similar to issue #165, the current checks against /etc/modprobe.d (e.g., 1.1.1.* in CentOS 7 CIS V2.1.0) can produce both false positives and false negatives.

CIS benchmark audit uses lsmod.  Also similar to #165, we can use /proc/modules for OS' using a Linux  kernel.

**Comment by whackyhack** [comment]
There are more problems than just source of truth.  This group is designed as blacklist in CIS benchmarks but implemented as whitelist.  This would give the exact opposite output if not for yet another problem, the inclusion of "match_output: /bin/true" which is never satisfied. (Hence the implementation produces perpetual false negatives.)

**Comment by basepi** [comment]
Good catch! Thanks for the report.

**Comment by whackyhack** [comment]
Fixed in hubblestack_data PR 60
