### ISSUE TITLE
Os_version mismatch with the one reported from vulners.com 

### ISSUE THREAD

**Issue by chrispetsos** [hubblestack/hubble#181]
Vulners.com reports 'OSVersion' as found in 'osrelease' grain rather than as in 'osmajorrelease'.

This is an expert of my Ubuntu 14.04 minion grains,

>     os:
>         Ubuntu
>     os_family:
>         Debian
>     osarch:
>         amd64
>     oscodename:
>         trusty
>     osfinger:
>         Ubuntu-14.04
>     osfullname:
>         Ubuntu
>     osmajorrelease:
>         14
>     osrelease:
>         14.04
>     osrelease_info:
>         - 14
>         - 4

Now, download the CVEs for this machine from,
http://vulners.com/api/v3/archive/distributive/?os=ubuntu&version=14.04
You'll notice how OSVersion is reported,

>       "affectedPackage": [
>         {
>           "OS": "Ubuntu",
>           "OSVersion": "14.04",
>           "packageVersion": "1.0.10-0ubuntu1.1",
>           "arch": "noarch",
>           "packageFilename": "UNKNOWN",
>           "packageName": "lxc",
>           "operator": "lt"
>         }
>       ]

See that it matches with the 'osrelease' grain rather than with the 'osmajorrelease'.
So, using 'osmajorrelease' first and then falling back to 'osrelease' as epxressed here,
https://github.com/hubblestack/hubble-salt/blob/develop/hubblestack_nova/cve_scan_v2.py#L99-L101
might lead to mismatch in this comparison,
https://github.com/hubblestack/hubble-salt/blob/develop/hubblestack_nova/cve_scan_v2.py#L272
leaving out vulnerability audits.

**Comment by basepi** [comment]
Thanks for the catch and the fix!
