### ISSUE TITLE
Allow the ability to whitelist packages for CVE scans.

### ISSUE THREAD

**Issue by chrispetsos** [hubblestack/hubble#182]
Imagine the following use case:
- Package X is found vulnerable during the CVE audit.
- Upgrading package X imposes a rather large update in the whole OS, so I decide not to upgrade it.
- Package X's vulnerability does not affect me very much, in the sense that I can live with it.

Allow me to whitelist package X so that it does not get reported as vulnerable during audits.

**Comment by basepi** [comment]
Very good use case. I left a comment on your PR -- easy fix and then we'll get it in!

**Comment by chrispetsos** [comment]
OK, done.
