### ISSUE TITLE
Error reporting for yaml errors in hubblestack_data

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#183]
Ref https://github.com/hubblestack/hubble/issues/180

YAML errors, such as the one caused by the `\d` inside of double quotes as shown below, are not being logged by the hubble loader. We need to log these errors or we can't know what's wrong with our profiles.

```
    sshd_idle_timeout:
      data:
        CentOS Linux-7:
        - /etc/ssh/sshd_config:
            match_output: "^ClientAliveInterval +[1-3]{0,1}\d{1,2}$"
            match_output_regex: True
            pattern: ^ClientAliveInterval
            tag: CIS-5.2.13
```

cc @whackyhack

**Comment by basepi** [comment]
Ha! I already did this and forgot about it...... https://github.com/hubblestack/hubble/pull/153/files

**Comment by whackyhack** [comment]
Fantastic!  Since they are Python, can I copy the 5 changed files into my RPM deployed servers? (Or, just one server for testing.)

**Comment by basepi** [comment]
It might work, though if you're using our RPMs then they're built with pyinstaller, and the pyinstaller magic could potentially break the normal modularity of python -- I'm not sure.

In any case, the only file you need is `nova_loader.py`. The others are unrelated to this fix.
