### ISSUE TITLE
CVE audit returns less vulnerabilities than those on vulners.com

### ISSUE THREAD

**Issue by chrispetsos** [hubblestack/hubble#184]
I have a CentOS salt minion which I perform CVE audits on. I currently get 7 vulnerabilities on it. I perform the checks for this machine on vulners.com with the method described here,
https://vulners.com/audit
and I get 10 vulnerabilities. After a close observation of the two results, I see that the hubble-salt CVE audit returns only one, single vulnerability for a package which my machine has several versions of, while vulners.com returns one vulnerability for every version, thus the increased number of vulnerabilities.

Is "multiple package versions -> single vulnerability" the intended behaviour in hubble-salt? If yes, could someone explain the rationale behind this decision?

**Comment by basepi** [comment]
I'm guessing it just finds the first one that matches and returns that. It's not an intentional design decision.

I wonder if the vulners_scanner (cve_scan_v3.yaml) would return all 10? That version uses their newer API.

**Comment by chrispetsos** [comment]
Well, even if v3 of cve scan returns the correct vulnerabilities, it
doesn't cover our use case. Our minions don't have internet connectivity so
they cannot just POST to vulners.com API. We like the idea of v2 with
offline audits from static json files served from the salt master. How
about me patching the v2 scan so that it returns vulnerabilities for all
versions of a package for this issue?

On Sep 14, 2017 10:29 PM, "Colton Myers" <notifications@github.com> wrote:

I'm guessing it just finds the first one that matches and returns that.
It's not an intentional design decision.

I wonder if the vulners_scanner (cve_scan_v3.yaml) would return all 10?
That version uses their newer API.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hubblestack/hubble/issues/184#issuecomment-329585014>,
or mute the thread

**Comment by basepi** [comment]
That would be awesome. I was mostly just curious if the v3 had the same issue, but I bet it doesn't since it sends the package information to vulners for procvessing.

**Comment by basepi** [comment]
I'm almost certain this has been fixed with the vulners scanner. We now use the vulners API through their python package.
