### ISSUE TITLE
False negative, false positive in Nova CIS scan for sshd_gracetime

### ISSUE THREAD

**Issue by whackyhack** [hubblestack/hubble#188]
Like several others, this one uses literal output_match, leading to possible false negatives and false positives.  In some profiles, pattern is not anchored to exclude comment lines, which leads to more possible false negatives. (I already have a patch using regex.)

**Comment by whackyhack** [comment]
Some other checks also have `pattern` anchoring-literal `match_output` combinations, leading to more possible negatives.  At least for sshd_config checks, they all should be `pattern`-anchored or regex.   I'll be examining them when I get leisure time.

**Comment by basepi** [comment]
Fixed by https://github.com/hubblestack/hubblestack_data/pull/68

**Comment by basepi** [comment]
And thank you, @whackyhack! You've been doing amazing work.

**Comment by whackyhack** [comment]
No problem - I should mention that I'm grateful that my employer, ThreatMetrix, is allowing me to cover the extended set.
