### ISSUE TITLE
grep.py TypeError: 'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by Inveracity** [hubblestack/hubble#191]
Heya, I'm getting the following error when i run `hubble.top`

```yaml
local:
    ----------
    Compliance:
        68%
    Errors:
        |_
          ----------
          /grep.py:
              ----------
              data:
                  TypeError: 'in <string>' requires string as left operand, not int
              error:
                  exception occurred
```

I tried the develop branch and the 2017.8.3 branch (hubble-salt)

**Comment by basepi** [comment]
Can you try running `salt-call hubble.top -ldebug` and see if there's a better stacktrace in the logs for that error? If you'd prefer you can just gist.github.com the results and I can look through.

**Comment by Inveracity** [comment]
Apologies for the wait, here's the full debug output:

https://gist.github.com/Inveracity/c1b5c3eda1efebb51dfaf01ea06fb179#file-hubble-top-debug-output-L421

Thank you

**Comment by Inveracity** [comment]
it turns out that 
```
tag_data['match_output']
```

is an integer if the value is 0

added the debug lines:
```python
#debug output
log.debug(repr(tag_data['match_output']))
log.debug(repr(grep_ret))
```

when the tag_data is a 0, it's interpreted as an integer:
```
[DEBUG   ] 0
[DEBUG   ] ''
```

however, when it's anything else, it's interpreted as a string
```
[DEBUG   ] '7'
[DEBUG   ] '#\tPASS_MIN_DAYS\tMinimum number of days allowed between password changes.\nPASS_MIN_DAYS\t0'
```

**Comment by basepi** [comment]
Odd. We should just surround the 0 with quotes in the yaml, that should fix this.

**Comment by basepi** [comment]
I think these instances have been resolved, I did a quick check on one of the profiles and couldn't find any unquoted zeroes. Please comment if that's not the case and we can reopen.
