### ISSUE TITLE
return cpu time spent running a task (nebula, or other applicable module)

### ISSUE THREAD

**Issue by fossam** [hubblestack/hubble#199]
To know better when tasks/queries are taking longer than expected or reasonable, report time cpu has spent on it.

It needs to be decided if a good place to do this is in the sourcetype=hubble_log or with every applicable event. But there has to be a way to link the offending task with the data about it.

**Comment by basepi** [comment]
I mean, we'll have the host information, and nothing except pulsar runs more often than 15 minutes, so dumping it into log should be fine.

I wonder if Python can do any of this monitoring, or if we'll just have to wrap all of our nebula queries in `time`?

**Comment by mew1033** [comment]
It'd be cool if we could report how long tasks are taking _while they're still running_. Then we can have an alert that fires if tasks are taking longer than x.
However, that might require multithreading or multiprocessing, which I know we've been trying to avoid...

**Comment by basepi** [comment]
We won't be avoiding it forever, I've just been focusing on the low-hanging fruit.

But why do we care while they're running? Assuming they eventually exit, we'll know how long it took, and we're not watching closely enough for real-time events to be actually useful. If they don't eventually exit, the host will disappear from splunk and we'll catch it that way.

**Comment by mew1033** [comment]
I guess that's true. I was thinking it'd be a good way to quickly identify rogue queries.

**Comment by basepi** [comment]
It would be cool, but I think introduces unnecessary complexity to whatever multiprocessing system we eventually go with. If it's super easy to add when we switch to a parallel architecture then I'm fine with adding it, I just don't think it's worth working hard for.

**Comment by fossam** [comment]
This request is solely based on the issue that there is no feedback when a query or a task takes long time to return. Being blind to performance impacts of the things Hubble runs should be avoided. It is  hard to foresee all possible situations so this kind of data should give good insight.

In short, the issue just states the need for this data and is agnostic to underlying implementation or software architecture. Therefore, having this issue for a dependency for another road map item (or vice versa) is totally fine by me.

**Comment by basepi** [comment]
We now have upper limits on jobs. I think we've decided to go that route for now -- we can re-open this if we decide to add more metrics.
