### ISSUE TITLE
ability to get output from commands/queries from things other than osquery

### ISSUE THREAD

**Issue by fossam** [hubblestack/hubble#200]
At times osquery can't give specific data that we're looking for. Well vetted and safely run commands can give additional data that can be very useful. 
The commands/queries would be similar to the nature of commands that run under _nova_ modules.

**Comment by basepi** [comment]
So is this going to be another `misc.py` module but for nebula? I'm not sure how else to do this without shipping actual commands in hubblestack_data. You can't have something that can execute generic commands without having a security issue.

**Comment by basepi** [comment]
So after talking further with Andres, we anticipate chaining together multiple safe functions in a similar way that I do in the [nova command module](https://github.com/hubblestack/hubble/blob/develop/hubblestack/files/hubblestack_nova/command.py). We'd have a nebula.awk and a nebula.netstat, etc, that we can chain together with ands and ors. I'm not sure if this belongs in nova or nebula....it depends on whether it will be designed to give us a final verdict of success and failure (nova), or if it will just collect data (nebula)

**Comment by basepi** [comment]
This is solved by flexible data gathering
