### ISSUE TITLE
CentOS 7 RPM should run daemon-reload in post-install

### ISSUE THREAD

**Issue by whackyhack** [hubblestack/hubble#201]
`
systemctl daemon-reload
`
Otherwise systemd would not recognize installed service unit.

**Comment by fossam** [comment]
fpm capability - lines in question:
https://github.com/hubblestack/hubble/blob/03ed98c39ec6256b732768f3bf87a4efa8e43241/pkg/centos7/Dockerfile#L136-L142

**Comment by basepi** [comment]
HOLY CRAP when did github start actually embedding linked code blocks? That's amazing!

I'm not sure what we'll have to do in fpm to get this done. I assume it has some sort of post install flag. We'll do some looking. I know how to do it in a specfile, just not with fpm.

**Comment by mew1033** [comment]
Fixed in https://github.com/hubblestack/hubble/pull/221
