### ISSUE TITLE
Hubble 2.2.8 not functioning properly with azure machines

### ISSUE THREAD

**Issue by yassingh** [hubblestack/hubble#224]
I tried running hubble 2.2.8 on centos 6 and 7 ( on azure machines ). I encountered following issues

On centos6 ( azure ):
Hubble commands are not running at all. 
```
[root@yassinghCentos6 centos]# hubble --version
hubble: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/hubble/hubble-libs/libz.so.1)
[root@yassinghCentos6 centos]# hubble hubble.audit
hubble: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/hubble/hubble-libs/libz.so.1)
``` 

On centos7 ( azure ):
on running hubble.audit, all sysctl commands are failing with following error:
```
[ERROR   ] Command 'sysctl -n net.ipv4.conf.default.rp_filter' failed with return code: 1
[ERROR   ] output: sysctl: /opt/hubble/hubble-libs/libelf.so.1: version `ELFUTILS_1.7' not found (required by /lib64/libdw.so.1)
```

However, hubble 2.2.8 is working fine on centos7 AWS.
Moreover, 'sysctl' command is itself working totally fine on centos7 terminal. Only when it is run under hubble module, it fails to run.

**Comment by sumanmehta** [comment]
Could it be related to the CentOS version on which Hubble was built? It seems it is not able to find a library which it was able to find at compile time.

**Comment by sumanmehta** [comment]
On Azure CentOS version 7.3, it worked fine for me.  Is it possible to make it compatible with both 7.1 and 7.3?

**Comment by basepi** [comment]
Sounds good. I can't reproduce on CentOS 7.3 either. The centos 7 stuff might be similar to the amazon linux issues we had at ont point where hubble was including rpmlib which was causing rpm to have problems when run under hubble. If that's the case it should be pretty easy to fix in the same way we fixed the rpmlib issue (removing the library at build time)

**Comment by basepi** [comment]
I'm going to see if I can find a centos6 server in azure to test with.

**Comment by basepi** [comment]
(You could test my centos7 hypothesis by removing the copies of that libelf library from the hubble-libs directory)

**Comment by basepi** [comment]
I can't reproduce on CentOS 6.8.

```
[root@ins3.wa1 ~]# hubble --version
2.2.8
[root@ins3.wa1 ~]# hubble grains.get lsb_distrib_release
'6.8'
```

**Comment by basepi** [comment]
(wa1 is one of our azure sites)

**Comment by yassingh** [comment]
i deleted the file /opt/hubble/hubble-libs/libelf.so.1
hubble.audit is running smoothly now ( sysctl module also working fine ) 👍 
your "centos7 hypothesis" seems correct

**Comment by yassingh** [comment]
hi everyone, i just realized that it was a blunder from my side. I was trying to run a  wrong hubble build on centos7/6.It was actually meant to be installed on amazon linux os only. 
Apologies for wasting your time and effort.
Now I have installed the correct hubble 2.2.8 build on centos 7 and 6, and it is working fine on azure as well as aws machines.
It is not a bug anymore, feel free to close it.
