### ISSUE TITLE
Benchmark shows as failed even though the results match

### ISSUE THREAD

**Issue by SaltyCharles** [hubblestack/hubble#226]
Windows 10 Custom Compliance Audit:
Module: `win_secedit.py`

Profile:
```profile_system_performance:
      data:
        'Microsoft Windows 10*':
        - SeSystemProfilePrivilege:
            match_output: 'Administrators,NT SERVICE\WdiServiceHost'
            tag: CIS-2.2.35
            value_type: account
      description: (l1) ensure 'profile system performance' is set to 'administrators,
        nt service\wdiservicehost'```

Failed output:

```{
                            "CIS-2.2.35": {
                                "description": "(l1) ensure 'profile system performance' is set to 'administrators, nt service\\wdiservicehost'",
                                "found_value": "*S-1-5-32-544,*S-1-5-80-3139157870-2983391045-3678747466-658725712-1809340420",
                                "match_output": "Administrators,NT SERVICE\\WdiServiceHost",
                                "module": "win_secedit",
                                "name": "SeSystemProfilePrivilege",
                                "nova_profile": "windows-10-enterprise",
                                "tag": "CIS-2.2.35",
                                "type": "whitelist",
                                "value_type": "account"
                            }
                        }```

Using the SIDs in `match_output` also results in a failure (obviously)

**Comment by basepi** [comment]
@madchills This is already on your radar, right?

**Comment by madchills** [comment]
Yes, this is something I am working on over the next 2 weeks.  I should have a fix for it soon

**Comment by alexpeay** [comment]
We are seeing this more and more as we roll hubble out, have you been able to isolate the issue? Are there any updates?

**Comment by basepi** [comment]
I feel like we might have gotten this fixed but I'll check with @madchills

**Comment by madchills** [comment]
This is a 2 part fix.  The first is the fix for putting the SID directly into the YAML and having it match correctly.  This has been fixed in my most recent pull request https://github.com/hubblestack/hubble/pull/275

The second fix will be to put the SID directly into the yaml for matching.  There is no good way to have windows pull the sid of 'NT SERVICE\WdiServiceHost'.  So putting the SID directly into the yaml should fix this problem. This will be added shortly

**Comment by basepi** [comment]
I'm pretty sure this one was fixed and we forgot to close this. Please comment if that's not so.
