### ISSUE TITLE
No way to provide 'less/greater than' option in  win_firewall

### ISSUE THREAD

**Issue by yassingh** [hubblestack/hubble#231]
Consider the following check in 'windows-2016-level-1-scored-v1-0-0.yaml' : 
```
win_firewall:
  whitelist:
    windows_firewall_domain_logging_size_limit :
      data:
        'Microsoft Windows Server 2016*':
          - 'LogMaxSizeKilobytes':
              tag: CIS-9.1.8
              match_output: '16384'
              value_type: 'domain'
      description: (l1) ensure 'windows firewall - domain - logging - size limit (kb)' is set to '16,384 kb or greater'
```
This check would fail is the logging-size is set to some value higher than 16384.  But the higher values should also pass this test as per CIS benchmark. Is there any way to allow to higher values as well ? 
( Unlike the win_secedit module, here 'value_type' can't be used to specify less/greater than option )
Is there any hack to make it work with higher values as well?

**Comment by madchills** [comment]
https://github.com/hubblestack/hubble/commit/0aa34845fc07605f240f5d2c975bdefd8c1af67e
