### ISSUE TITLE
Automatically manage and report a profile version string.

### ISSUE THREAD

**Issue by fossam** [hubblestack/hubble#243]
Currently on the siem side it is cumbersome to determine if a host has up to date hubblestack_data profile. Searching for missing fields or manually managing a query for profile version string can be error prone. 

Hubble should deterministically come up with a profile version string and report it regularly.

**Comment by fossam** [comment]
Wouldn't a version file be still a manual process?

One option is to depend on hashes of files in the hubblestack_data and somehow report their changes. _hubble_log_ might work.

**Comment by basepi** [comment]
Yes, the version file would be manual. Hashes could also work. We just need something concrete, and even if it's manual it means we can give ourselves milestones when we need them.

**Comment by basepi** [comment]
I think we're doing this now via osquery.
