### ISSUE TITLE
This is not PEP 8 Compliant

### ISSUE THREAD

**Issue by mattharrison** [hubblestack/hubble#250]
[Redacted] wanted me to tell you this. This is keeping her up at night.

https://github.com/hubblestack/hubble/blob/725722611c6dd01ef508fccb7f9e2bc1a73ac4dc/hubblestack/splunklogging.py#L194

**Comment by basepi** [comment]
Hahahaha then tell [Redacted] to send in a PR!

(In my defense, that's not my code! Except it's in my project, so I guess it's my code.)

**Comment by basepi** [comment]
Also, [obligatory link](https://www.youtube.com/watch?v=wf-BqAjZb8M)

**Comment by basepi** [comment]
We've fixed a bunch of these and will fix the rest once we enable travis linting. I'm going to close this issue. :)
