### ISSUE TITLE
Logo Idea 

### ISSUE THREAD

**Issue by timkim** [hubblestack/hubble#252]
Hey there @basepi 

We met briefly at the Adobe Open Source Summit and I said I was interested in creating you a logo for this project. I think I remember you asking for something flattish design? In any case, I've come up with an idea attached here. Let me know if this is something that you're looking for. 

Large:
![hubble2-sized](https://user-images.githubusercontent.com/57922/33405969-73aee13c-d51f-11e7-8d54-bb7ff04f8edf.png)

Small:
![hubble2-sized-small](https://user-images.githubusercontent.com/57922/33406029-ce36c6ec-d51f-11e7-8178-ce20552a2a3a.png)

**Comment by basepi** [comment]
This is pretty awesome! I wish I were more artistic.

The logo itself looks great but is a touch busy, especially when it's small. It also doesn't really evoke a connection with hubblestack outside of the space telescope theme -- I wonder if we could modify the dimensions to evoke more of an H shape.

For example, this is one that we've been looking at:

![hubblestack-h](https://user-images.githubusercontent.com/702318/33457172-e14d5056-d5de-11e7-89cd-2c7c563d9974.png)

It kind of is reminiscent of a satellite, but is still very recognizable as an H as well. It's modified from one of the monograms available on logojoy. I'm still on the prowl for something that makes me go "that's the one!" but I think even simpler is the direction we'd like to go.

**Comment by fossam** [comment]
I think overall timkim's design is pretty to look at and fits great on stickers. If we want to fit it into a favicon format it cold lose details like the solar panel grids, but that's for really small formats.

**Comment by basepi** [comment]
Ooh, yeah, now I really want a sticker! We may have to try to find a way to incorporate both, maybe for different uses.

**Comment by basepi** [comment]
@timkim any chance you have an SVG version I could toy with?

**Comment by timkim** [comment]
Yep - attached is a zip of the svg and ai files. 
[hubble.zip](https://github.com/hubblestack/hubble/files/1523178/hubble.zip)

I'll see what I can come up with the H shape in mind.

**Comment by timkim** [comment]
Ok, here's another iteration of the logo. I have kept in mind the H shape and the busyness of the previous attempt. We can talk about colours next if you like the shape of this design. 

![hubble3_bw](https://user-images.githubusercontent.com/57922/33636525-6e3e7fe4-d9d1-11e7-8292-db52456ab66d.png)
![hubble3_bw_small](https://user-images.githubusercontent.com/57922/33636527-71134010-d9d1-11e7-9401-0710b49f4576.png)

**Comment by basepi** [comment]
Ooh, I like this one quite a bit. Once we get some color in it it could be really awesome! @cedwards thoughts?

**Comment by timkim** [comment]
Okie dokie, here's a colour scheme that I'm trying. Still playing around with it, but I'm liking it. 
![artboard 1](https://user-images.githubusercontent.com/57922/33856731-e4b71d2e-de7d-11e7-8b0c-bf6cf522a600.png)

**Comment by basepi** [comment]
I'm not sure I'm digging the yellow, but I'm also not sure what I would replace it with.... turns out I'm not a designer.

**Comment by timkim** [comment]
We can go red or just go with a circle. 

![artboard 1 4x](https://user-images.githubusercontent.com/57922/34131008-ce6496b0-e3fe-11e7-971f-ba914b5e0852.png)
![artboard 1 4x](https://user-images.githubusercontent.com/57922/34131017-d3277e7e-e3fe-11e7-9200-317194a84b44.png)

**Comment by mew1033** [comment]
I like the yellow or the white. Not loving the red though.

**Comment by basepi** [comment]
Yeah, red didn't do it either. White is probably my favorite. @cedwards any thoughts?

**Comment by fossam** [comment]
Comparison - the first one looks the the best, aesthetically speaking.
But the latest one has the idea of eye being in the middle. My only suggestion is to try and see how it looks with a dark background and somehow change/make the Hubble colors work with that. I think that would make the eye stand out more.

**Comment by timkim** [comment]
Ok, I've reworked the design to be just flat and simple. I think the colours and the eye were taking away from the design. 

Here's what it looks on a dark background:
![artboard 1 0 5x](https://user-images.githubusercontent.com/57922/34545060-02ce5588-f09f-11e7-903c-89adf530980f.png)

And I've also tested it on the website and I think it fits the website's theme nicely as well:
<img width="1320" alt="screen shot 2018-01-03 at 3 58 17 pm" src="https://user-images.githubusercontent.com/57922/34545083-22b3e0ac-f09f-11e7-9cd5-12bf8cee3840.png">

**Comment by basepi** [comment]
I think we've mostly settled on the logo that's currently on our org, but these are good options for the future. Thanks @timkim!
