### ISSUE TITLE
'hubble.sync' is not available for SLES11 SP4 minions ( Specific to SUSE )

### ISSUE THREAD

**Issue by sam0104** [hubblestack/hubble#266]
**# salt '*' hubble.sync
minion1:
    'hubble.sync' is not available.
minion2:
    'hubble.sync' is not available.

# salt '*' hubble.audit
minion1:
    'hubble.audit' is not available.
minion2:
    'hubble.audit' is not available.**

We are using hubble module for audit and it is wokring fine for RHEL and Centos but on SLES linux hubble.sycn is not working. For SLES the official salt-minion version is salt-minion-2016.11.4-13.1.x86_64 . We do not have any updated version for SLES11 SP4.

Trouble shooting  

salt '*' saltutil.clear_cache
salt '*' saltutil.sync_all
salt '*' hubble.sync

tried above commands still no luck for SLES11 SP4 minions. 

**Salt master version 

**# salt-master --versions-report
Salt Version:
           Salt: 2017.7.2**

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

salt minion version on SLEL11 SP4 

**# /usr/bin/salt-minion --versions-report
Salt Version:
           Salt: 2016.11.4**

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Apr  7 2015, 08:28:12)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.8

System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-68-default
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64

hubble module is missing on SLES11SP4 minions while checking with sys.list_modules but on Centos6 and Centos7 I can see the hubble module without any issue.
# salt 'minion1' sys.list_modules
minion1:
    - acl
    - aliases
    - alternatives
    - appcontrol
    - archive
    - artifactory
    - at
    - beacons
    - blockdev
    - bridge
    - btrfs
    - buildout
    - certificates_import
    - cloud
    - cmd
    - composer
    - config
    - consul
    - container_resource
    - cp
    - cpan
    - cron
    - data
    - defaults
    - devmap
    - dig
    - disk
    - django
    - dnsmasq
    - dnsutil
    - drbd
    - elasticsearch
    - environ
    - etcd
    - ethtool
    - event
    - extfs
    - file
    - gem
    - genesis
    - grains
    - group
    - grub
    - hashutil
    - hipchat
    - hosts
    - http
    - img
    - incron
    - ini
    - inspector
    - introspect
    - ip
    - iptables
    - iwtools
    - jboss7
    - jboss7_cli
    - k8s
    - key
    - kmod
    - locale
    - locate
    - logrotate
    - lowpkg
    - lvm
    - match
    - mine
    - minion
    - modjk
    - mount
    - nagios_rpc
    - network
    - nfs3
    - nova_loader
    - openscap
    - openstack_config
    - oscap
    - pagerduty
    - pam
    - partition
    - pillar
    - pip
    - pkg
    - pkg_resource
    - postfix
    - postgres_cfg
    - ps
    - publish
    - puppet
    - pushover
    - pyenv
    - quota
    - raid
    - random
    - random_org
    - rbenv
    - rest_sample_utils
    - restartcheck
    - ret
    - rsync
    - rvm
    - s3
    - s6
    - salt_proxy
    - saltutil
    - schedule
    - scsi
    - sdb
    - seed
    - sensors
    - service
    - shadow
    - slack
    - slsutil
    - smbios
    - smtp
    - sqlite3
    - ssh
    - state
    - status
    - supervisord
    - sys
    - sysctl
    - sysfs
    - syslog_ng
    - system
    - temp
    - test
    - timezone
    - tomcat_cfg
    - udev
    - user
    - vbox_guest
    - virtualenv
    - x509
    - xfs

**Comment by basepi** [comment]
On the minion, can you do `salt-call hubble.sync -ldebug` please? I wonder if something is stacktracing at load time.

Also, did hubble.py show up in the sync results when you first did the saltutil.sync_all? You can clear the minion cache and re-sync to see fresh results.

**Comment by sam0104** [comment]
Is there any update on this issue ?

**Comment by basepi** [comment]
Sorry for the delay. This seems like an incompatible version of salt -- notice the `import requests` and `import six` lines that are failing in those logs. Salt (and hubble) definitely require those libraries, so something weird is going on.

Ideally you should be able to open a python shell, and do the following imports with no errors:

```
import salt
import requests
import six
```

Unfortunately I don't have any SLES experience so I'm not going to be much help fixing this issue.

Out of curiosity, what does `salt-call --versions-report` show on that minion?

**Comment by sam0104** [comment]
Here is Python import output from SLES VM 

hdbdb:~ # python
Python 2.6.9 (unknown, Apr  7 2015, 08:28:12)
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named requests
>>> import six
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named six
>>>

**Comment by sam0104** [comment]
Here is salt-call command output 

hdbdb:~ # salt-call --versions-report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Apr  7 2015, 08:28:12)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.8

System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-68-default
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64

hdbdb:~ #

**Comment by sam0104** [comment]
I can see in SLES VMs six and requests python modules were missing. I installed them using pip and restarted salt-minion service and now hubble.audit is working fine. Thanks for pointing to the root cause. 
I will close this issue as no further action is required. 

Fix 👍 👍 
zypper install python-pip
On SLES minion : 
pip install six
pip install requests
service salt-minion restart

on Salt-Master:
salt '*' saltutil.clear_cache
salt '*' saltutil.sync_all
salt '*' hubble.sync

Test hubble.audit:
salt hdbdb.lab04.local hubble.audit
hdbdb.lab04.local:
    ----------
    Compliance:
        38%

**Comment by basepi** [comment]
Awesome! Glad you figured it out. Weird that salt didn't ship with requests.... It's still listed as a dependency on their installation docs.

**Comment by sam0104** [comment]
It could be the issue with salt minion for SUSE only as it has older version (2016) compare to other Linux flavor. Is there a way to verify if SUSE salt minion has these three modules as part of installation ?

**Comment by sam0104** [comment]
From Saltstack official repo for SUSE11 SP4 I could not find requests module . 
http://repo.saltstack.com/opensuse/SLE_11_SP4/

**Comment by basepi** [comment]
It appears to be there for the centos/debian/ubuntu builds. Not sure why it would be missing from SUSE. Guess we may have to add an installation note. Requests is definitely required for hubble. (And I sure thought it was required for salt)
