### ISSUE TITLE
Benchmark is not getting a found_value

### ISSUE THREAD

**Issue by alexpeay** [hubblestack/hubble#267]
We are working on a set of checks that are trying to confirm that no user has access or permissions to take a specific action. These checks are all failing because we are not getting a found_value returned to us.  It may be that Windows is returning an empty set, which would be successful since no user (No One) has rights to do the specified thing, but since we do not have a found_value we can not be sure.

here is an example return for the item in question: 
{
                            "CIS-2.2.13": {
                                "description": "(L1) Ensure 'Create permanent shared objects' is set to 'No One'",
                                "match_output": "No One",
                                "module": "win_secedit",
                                "name": "SeCreatePermanentPrivilege",
                                "nova_profile": "windows-10-enterprise-r1703-level-1",
                                "tag": "CIS-2.2.13",
                                "type": "whitelist",
                                "value_type": "match"
                            }

**Comment by basepi** [comment]
@madchills can you see if you can reproduce when you have a moment?

**Comment by basepi** [comment]
Pretty sure salt isn't using our profiles anymore so I'm going to close this one. Please comment if it should be reopened.
