### ISSUE TITLE
Getting InsecureRequestWarning warning in hubble log

### ISSUE THREAD

**Issue by anuragpaliwal80** [hubblestack/hubble#279]
I think we have discussed this before, logging the ticket to keep track of this issue.
hubble log file shows:

`[py.warnings    ][WARNING ] /opt/hubble/hubble-libs/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`

**Comment by basepi** [comment]
I think we've resolved this by just enabling SSL by default.
