### ISSUE TITLE
Typo on system_account_non_login

### ISSUE THREAD

**Issue by wschmrdrNS** [hubblestack/hubble#281]
In misc.py for Nova, the function system_account_non_login is looking for "/sbin/nologin", while the CIS Ubuntu Linux 16.04 LTS Benchmark v1.1.0 spec that has a similar script check under CIS-5.4.2 is looking for "/usr/sbin/nologin". This is coming up as a False Flag when running this function against Ubuntu 16.04, while a manual run using the script in the spec comes out as a Pass.

**Comment by basepi** [comment]
@yassingh Would you mind looking at this one when you get a chance? It looks like this is mostly your code.

**Comment by yassingh** [comment]
Sure. I will take it from here.

**Comment by yassingh** [comment]
You are right @wschmrdrNS . In misc.py, the  system_account_non_login function is looking for "/sbin/nologin". But CIS spec is asking to look for "/usr/sbin/nologin". 
So, I have already modified misc.py. Now the the path to non-login shell can be passed using a parameter. For example: 
https://github.com/hubblestack/hubblestack_data/blob/develop/hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml#L1037

The code change is already in place. The problem should be resolved once a new build for ubuntu16 is released with updated code.

**Comment by wschmrdrNS** [comment]
Is the hubble-salt project also going to be updated to account for this? We are presently using that in order to hook into the nodes that our master already has.

**Comment by yassingh** [comment]
> Is the hubble-salt project also going to be updated to account for this?

I guess so. 
But I am not the correct person to give any commitment about it.  
@basepi can provide more info about "hubble-salt"/"hubble" syncing process.

**Comment by basepi** [comment]
Yes, we'll make sure we get it backported. Actually I should probably go through all the modules before our next release and make sure the changes get backported where possible.

**Comment by basepi** [comment]
I can't remember if we've backported this or not but we ended up deprecating hubble-salt. Sorry for any inconvenience that caused.
