### ISSUE TITLE
gitFS constructor error

### ISSUE THREAD

**Issue by yassingh** [hubblestack/hubble#313]
I was trying to run a build created with the latest code in develop branch. I got an error looking like this:
```
File "hubble.py", line 5, in <module>
  File "hubblestack/daemon.py", line 71, in run
  File "hubblestack/daemon.py", line 90, in main
TypeError: __init__() takes exactly 2 arguments (5 given)
```
It seems to be related to this code change:
https://github.com/hubblestack/hubble/commit/ed2349e519e59965b30bdc45f52e2188adb20921

**Comment by jettero** [comment]
I ran into this yesterday myself. I was just testing on a branch and got the above. pip installed 2017.x.x and it had the unknown init form. I slogged through a bunch of the  history in 2017 and never did find that older form.

This morning, pip seems to be installing 2018.3rc0. Try `pip install --upgrade salt-ssh` and see if this goes away?

**Comment by basepi** [comment]
It appears that all the arguments have defaults in the new code, so I think I can fix this for backwards compat. Or we can just peg to the new version of salt since we own the dependency chain with our pyinstaller packages.

**Comment by basepi** [comment]
Scratch that. The default arguments will not give me the results I want. For now, upgrade your version of salt-ssh and when we're prepping the release we can see if it breaks anything.

**Comment by yassingh** [comment]
No problem 👍 
Just wanted to bring this thing to notice.
( Feel free to close the issue )
