### ISSUE TITLE
[ERROR ] Command 'mount' failed

### ISSUE THREAD

**Issue by anuragpaliwal80** [hubblestack/hubble#385]
We are seeing the following error. Looks like due to https://github.com/hubblestack/hubble/blob/develop/hubblestack/files/hubblestack_nova/misc.py#L370

```
[ERROR ] Command 'mount' failed with return code: 1
[ERROR ] output: mount: /opt/hubble/hubble-libs/libmount.so.1: version `MOUNT_2.30' not found (required by mount)
```

After deleting this, it works fine.
Looks like it worked fine because mount command is working directly on the system but if it's missing on OS, then our function will not work (if we delete the file).

**Comment by anuragpaliwal80** [comment]
I am not 100% on how libmount.so.1 is getting installed inside our hubble-libs dir. May be because of mount.py module or command.py or may be because of some thing else?

**Comment by fossam** [comment]
pyinstaller handles what files to include. It must be the differences of how different versions of pyinstaller do it, since for CentOS 6 for example, libmount.so was not included.

**Comment by basepi** [comment]
Yeah we should probably start a "remove if present" list for libraries that pyinstaller tries to include. I'm betting that's also the issue with the CentOS 7.5 issues that @anuragpaliwal80 found.

**Comment by fossam** [comment]
That list would be hard to maintain given that an arbitrary command can be issued. That is why I would avoid OS commands when possible. Shipping our own binaries would make dealing with dependencies from OS also easier.

**Comment by gjones623** [comment]
https://jira.corp.adobe.com/browse/CSTTEAM-44034

**Comment by basepi** [comment]
I'm going to close this since our long-term plan is to move away from misc.py to FDG, and we can solve it then.
