### ISSUE TITLE
Exception message too broad

### ISSUE THREAD

**Issue by zachsis** [hubblestack/hubble#403]
https://github.com/hubblestack/hubble/blob/44cf4a493bc74234980632116acfc2c66ad7569d/hubblestack/splunklogging.py#L361

Just a suggestion: While I was debugging why our hubble instance wouldn't connect to its splunk returner, I found this exception to be a little too vague to figure out what hubble was doing with the request/response. It Would be useful to print out the `requests.response.status_code` in the exception and the json response in `requests.response.content` if any.

**Comment by basepi** [comment]
This is a great suggestion. I agree that it's not super useful at the moment.

**Comment by ryandamour** [comment]
I just submitted PR #404 to address this - https://github.com/hubblestack/hubble/pull/404
