### ISSUE TITLE
[Help Wanted] Demo Setup for Hubble v2 with ELK Stack reporting

### ISSUE THREAD

**Issue by danielmihai** [hubblestack/hubble#419]
Hubble v1 was (really) well documented. Why isn't v2?
There's no doc on quasar anymore and it's referenced in the new v2 docs. Adobe, can you please make proper docs ? Don't turn the Hubble project into a Black Hole of Non-Documented good ideas. 

I want to present v2 in a week at a cross-meetup i'm organizing together with a security meetup group and the lack of docs isn't making my preparation easier. I think I'll have to go through hubble-salt docs again to remember how to do everything. Or maybe i'm just tired and don't see things in v2 readme. 

Thanks!

**Comment by basepi** [comment]
It has gone to the README: https://github.com/hubblestack/hubble/blob/develop/README.md

We do need to get the docs on the hubblestack website updated as well.

And you're right, we should add some returner docs to the README in the meantime. Maybe I'll do that later today....

**Comment by danielmihai** [comment]
Hi Colton @basepi,

I've read the current documentation, and thus, the open issue. Thanks for labelling the issue, forgot to do it! Please, help me set up comprehensive demo for Hubble v2, including reporting. I'll pitch the project and encourage people to contribute to the really nice project. I just joined the Hubble Slack workspace.
I watched all C.E. presentations from 05-05-2016 till now, to remember stuff. 

I previously (some time ago, 1-2 yr?) got v1 working, until the reporting part, which I couldn't get it to work.
Can someone, please, guide me with: 
1. How to install Hubble v2 on a number of machines, i=2,n with O(1) complexity :) 
2. Configure Hubble v2 to do CVE scanning and send the results to, let's say, ELK and Slack.

My presentation/demo is on Thursday. I know it's late, but I'll make it. 
Looking forward to your support and response! Good luck guys!

Thanks,
Daniel.

**Comment by danielmihai** [comment]
Hi @basepi , 

Thanks for the details! 

For 1. i'm using Terraform, without any configuration management, just for demoing the low sodium Hubble. I'm going to write some local config files, and add them via the remote executor of Terraform from my local machine. 

For 2. i'm going to config the topfile, scheduler and slack and logstash returners, and see if it works. 

Will get back to you after I do all of the above. 

Thanks a bunch for the support!     

Kind Regards,
Daniel

**Comment by danielmihai** [comment]
@basepi , should we keep this issue open or change the scope of it and create a new one for the actual documentation work ?

**Comment by basepi** [comment]
If you could close this one and create a new one for documentation updates around returners, that would be awesome.

**Comment by basepi** [comment]
Label is fine, nobody looks at closed issues
