### ISSUE TITLE
Update Hubble v2 Documentation

### ISSUE THREAD

**Issue by danielmihai** [hubblestack/hubble#426]
Hello, 

As a developer/devops person, I would like to be able to read the latest HubbleStack documentation, such that I can install, configure, add reporting, use, extend, integrate Hubble and its components easily. Previously, Hubble v1 was fairly well documented and users could manage on their own. 

Document all new features and ways of operating Hubble v2, including docs.hubblestack.io, readme.md in the repo and all other locations affected by the new version. 

Best Regards,
Daniel.

**Comment by basepi** [comment]
I recently did a pretty big overhaul of the docs. They're not perfect, but I think it's a good start and we'll keep working on it.
