### ISSUE TITLE
Vulners Python API support

### ISSUE THREAD

**Issue by vulnersCom** [hubblestack/hubble#438]
Hi fellows!
May I suggest you refactoring Vulners Scanner to the public [Vulners Python API](https://github.com/vulnersCom/api).
It's completely supported and I think will make it easier to integrate.
It's also [available via Pypi](https://pypi.org/project/vulners/).

**Comment by basepi** [comment]
Ooh, we should definitely do that. Thanks for the link! I think our latest CVE scanner uses your REST api, which I think was much better for your servers than downloading the json ourselves, but this sounds like it should be even better.
