### ISSUE TITLE
False positives for Ubuntu 16.04

### ISSUE THREAD

**Issue by ApertureSecurity** [hubblestack/hubble#489]
Hello, I when I run the `hubble hubble.audit` receive this...

```
[ERROR ] Command '[u'sysctl', u'-n', u'net.ipv6.conf.all.accept_ra']' failed with return code: 255
[ERROR ] stdout: sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_ra: No such file or directory
[ERROR ] retcode: 255
[ERROR ] Command 'sysctl -n net.ipv6.conf.all.accept_ra' failed with return code: 255
[ERROR ] output: sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_ra: No such file or directory
[ERROR ] Command '[u'sysctl', u'-n', u'net.ipv6.conf.default.accept_ra']' failed with return code: 255
[ERROR ] stdout: sysctl: cannot stat /proc/sys/net/ipv6/conf/default/accept_ra: No such file or directory
[ERROR ] retcode: 255
[ERROR ] Command 'sysctl -n net.ipv6.conf.default.accept_ra' failed with return code: 255
[ERROR ] output: sysctl: cannot stat /proc/sys/net/ipv6/conf/default/accept_ra: No such file or directory
[ERROR ] Command '[u'sysctl', u'-n', u'net.ipv6.conf.all.accept_redirects']' failed with return code: 255
[ERROR ] stdout: sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_redirects: No such file or directory
[ERROR ] retcode: 255
[ERROR ] Command 'sysctl -n net.ipv6.conf.all.accept_redirects' failed with return code: 255
[ERROR ] output: sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_redirects: No such file or directory
[ERROR ] Command '[u'sysctl', u'-n', u'net.ipv6.conf.default.accept_redirects']' failed with return code: 255
[ERROR ] stdout: sysctl: cannot stat /proc/sys/net/ipv6/conf/default/accept_redirects: No such file or directory
[ERROR ] retcode: 255
[ERROR ] Command 'sysctl -n net.ipv6.conf.default.accept_redirects' failed with return code: 255
[ERROR ] output: sysctl: cannot stat /proc/sys/net/ipv6/conf/default/accept_redirects: No such file or directory
{'Compliance': '67%',
'Controlled': [\{'CIS-5.4.2': 'Code change required for filtering the users by their login shell'}],
'Errors': [{'CIS-1.1.20': 'An error occurred exeuction function sticky_bit_on_world_writable_dirs: Module disabled due to performance concerns'},
```

All the IPV6 checks are failing and I think should be checked in the sysctl.conf as well for things like .

`net.ipv6.conf.all.forwarding=0  `

Has something like this been reported ? and what is a recommended solution for this?  Ultimately I wil be using this for a sort of Bill of environment health.

Thanks

**Comment by basepi** [comment]
I don't think those have been reported yet -- it's not one of the checks we're using as an indicator at Adobe (yet) so we haven't looked at it closely.

The recommended (fastest) solution would be for you to fix the checks [here](https://github.com/hubblestack/hubblestack_data/blob/develop/hubblestack_nova_profiles/cis/ubuntu-1604-level-1-scored-v1-0-0.yaml) and submit a PR. Otherwise we'll add this to our backlog.

**Comment by ApertureSecurity** [comment]
Ok. 

Thanks I will definitely take a look. I am extremely rusty with salt , so I will look and see what I can do and make a PR.

**Comment by basepi** [comment]
Luckily this is pure hubble "code" in those profiles. Unfortunately the format is terrible, but we're working on fixing that in the near(ish) future.

**Comment by ApertureSecurity** [comment]
So I have been evaluating this and it's not a FP as I initially thought. The system that I am working in doesnt have IPV6 at all enabled and therefore no IPV6  folder is populated in 

/proc/sys/net/

Is there a way to make exceptions in hubble?

**Comment by basepi** [comment]
Yep! You can use compensating controls to tell Hubble to ignore certain failures. Just stick `control:` into the check like this: https://github.com/hubblestack/hubblestack_data/blob/b849aa548542fe2e71eee6232f57df3053b9cda7/hubblestack_nova_profiles/samples/sample_control.yaml

You can also have a separate control file targeted by your topfile. These docs are old and need to be ported into the new doc system, but I think they're still valid: https://github.com/hubblestack/nova#compensating-control-configuration
