### ISSUE TITLE
Add returner information to the docs

### ISSUE THREAD

**Issue by alias454** [hubblestack/hubble#502]
Just getting started, I had to dig around a bit to find some information on how returners worked so adding some information to the docs would be helpful for others I think. I wrote this up as a brief snippet if you think it would be helpful.

> It is quite possible you may want to send the NOVA audit results to a collection system. This can be accomplished by using returners, which are included with Hubble. Currently, there are returners available for splunk, logstash, graylog, and sqlite. Hubble supports using multiple returners from the same node so sending data to multiple collectors is possible. Each returner has distinct options that need to be set prior to their use, which you can find the general config options for each returner at the top of each file located here https://github.com/hubblestack/hubble/tree/develop/hubblestack/extmods/returners.
>
> Specify a returner when running Hubble from the command line like this:
    hubble hubble.audit --r RETURN, --return RETURN
>
> You can also define schedules for returners in the Hubble config file, which is typically located at /etc/hubble/hubble.conf.

**Comment by basepi** [comment]
Yes! This would be an awesome addition. Would you mind making a PR to [the docs](https://github.com/hubblestack/hubble/tree/develop/doc) wherever you think it would have been the most useful for you?

**Comment by alias454** [comment]
Thanks, I added it here https://github.com/hubblestack/hubble/pull/508.
