### ISSUE TITLE
Inconsistent yaml section data

### ISSUE THREAD

**Issue by alias454** [hubblestack/hubble#535]
I'm not sure if this causes an issue within hubble or not but when trying to parse yaml files automatically with a custom script, I ran into some inconsistent sections. I see a few where items that are typically lists, are represented as dictionaries and others missing "tags" etc. 

Examples exist in amazon-201409-level-1-scored-v1-0-0.yaml and amazon-level-1-scored-v1-0-0.yaml files for missing list items.
```
     rsyslog:
       data:
         'Amazon Linux AMI-2014':
-          'rsyslog': 'CIS-5.1.1'
+          - 'rsyslog': 'CIS-5.1.1'
       description: 'Install rsyslog'
 
     anacron:
       data:
         'Amazon Linux AMI-2014':
-          'cronie-anacron': 'CIS-6.1.1'
+          - 'cronie-anacron': 'CIS-6.1.1'
       description: 'Enable anacron Daemon'
```

Another example is a couple of items missing the "tag" in ubuntu-1604-level-1-scored-v1-0-0.yaml. Everything else seems to use "tag" within the section
```
     ldap-server-disabled:
       data:
         Ubuntu-16.04:
-        - slapd: CIS-2.2.6
+        - slapd:
+            tag: CIS-2.2.6
       description: Ensure LDAP server is not enabled
     nfs-disabled:
       data:
         Ubuntu-16.04:
-        - nfs-kernel-server: CIS-2.2.7
+        - nfs-kernel-server:
+            tag:  CIS-2.2.7
       description: Ensure NFS and RPC are not enabled
```

I'm not sure how hubble handles these but they caused my parser to throw some errors. Of course, I can manage these changes locally but thought they might be worth bringing up.

Regards,
Brandon

**Comment by basepi** [comment]
Closing since https://github.com/hubblestack/hubble/issues/536 will resolve this.

**Comment by alias454** [comment]
Not sure if you are up for requests at this point but having a utility to convert existing audit files to the new format would be nice(whatever that may be).
