### ISSUE TITLE
Submitted PR to "fix" inconsistent yaml data

### ISSUE THREAD

**Issue by alias454** [hubblestack/hubble#538]
Since I was making these changes anyway, I figured this might be useful. I submitted a PR https://github.com/hubblestack/hubblestack_data/pull/133 related to  the oddities discussed here https://github.com/hubblestack/hubble/issues/535 and a few more.

Thanks,
Brandon

**Comment by alias454** [comment]
I went whole ham on these too

> Amazon_Linux_Benchmark_v210 (still needs PR submitted but done)
> CentOS_Linux_7_Benchmark_v220 (new version)
> Debian_Linux_9_Benchmark_v100 (new version)
> Distribution_Independent_Linux_Benchmark_v110 (updates and changes)
> Red_Hat_Enterprise_Linux_7_Benchmark_v220 (new version)
> Ubuntu_Linux_1604_LTS_Benchmark_v110 (new version)
> Ubuntu_Linux_1804_LTS_Benchmark_v100 (new version)

**Comment by basepi** [comment]
Awesome! I've merged all your PRs except one which started conflicting. Thank you again!
