### ISSUE TITLE
Pulsar functions not found - Windows

### ISSUE THREAD

**Issue by ufomorme** [hubblestack/hubble#549]
Hubble on Windows 10  - Pulsar functions not found:

2019-02-19 11:08:58 [hubblestack.daemon][ERROR   ] Scheduled job pulsar has a function pulsar.process which could not be found.

2019-02-19 11:09:08 [hubblestack.daemon][ERROR   ] Scheduled job pulsar_canary has a function pulsar.canary which could not be found.

Default install/config. Only Splunk info added to config.

**Comment by basepi** [comment]
Thanks for the report. I'm going to have @Tenebriso look into this.

**Comment by basepi** [comment]
https://jira.corp.adobe.com/browse/CSTTEAM-44494

**Comment by SpiritualMadMan** [comment]
I cannot access: https://jira.corp.adobe.com/browse/CSTTEAM-44494 because Secure Connection Failed SSL_ERROR_HANDSHAKE_FAILURE_ALERT

I've tried using Firefox; IE and Edge to no avail...

**Comment by basepi** [comment]
This is fixed in https://github.com/hubblestack/hubble/pull/601

**Comment by basepi** [comment]
(Also, note that those jira links are unfortunately to our instance behind Adobe VPN, so they will not be visible to non-Adobe employees.)
