### ISSUE TITLE
Nova pkg module is not working as expected

### ISSUE THREAD

**Issue by anuragpaliwal80** [hubblestack/hubble#65]
Command: `__salt__[‘pkg.version’](“openssh-server”)` return None but command `rpm -q “openssh-server”` returns openssh-server-6.6.1p1-25.61.amzn1.x86_64. Looks like something wrong in salt command ? As per my understanding the first command (the salt one) should return the version details. (Tried using pkg.py file)

**Comment by basepi** [comment]
What operating system is the host running? Does it show up in `yum list installed`? I'm pretty sure salt's pkg.version is using yum, not rpm. It's possible their results differ.

**Comment by anuragpaliwal80** [comment]
I was using Amazon Linux.
yes the above command `yum list installed` is working.
`__salt__['pkg.version']('openssh-server')` shows bank but if I use `__salt__['pkg.latest_version']('openssh-server'),` it shows error as 
`[ERROR   ] Command '['yum', '--quiet', 'clean', 'expire-cache']' failed with return code: 1
[ERROR   ] output: There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   /usr/lib64/python2.7/lib-dynload/_io.so: undefined symbol: _PyErr_ReplaceException

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

If you cannot solve this problem yourself, please go to 
the yum faq at:
  http://yum.baseurl.org/wiki/Faq
[ERROR   ] Problem encountered getting latest version for the following package(s): openssh-server. Stderr follows: 
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   /usr/lib64/python2.7/lib-dynload/_io.so: undefined symbol: _PyErr_ReplaceException

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

If you cannot solve this problem yourself, please go to 
the yum faq at:
  http://yum.baseurl.org/wiki/Faq`

**Comment by basepi** [comment]
Fascinating. Seems like it might be a salt error, I wonder if upgrading our underlying salt version might resolve this?

Also why is python involved at all if it's just shelling out to `yum --quiet clean expire-cache`? Very odd. I'll have to see if I can reproduce it.

You also might try installing salt and testing with `salt-call` just to see if you can reproduce in salt.

**Comment by basepi** [comment]
I can reproduce this. I'm betting it's something related to our pyinstaller build. I'm wondering if it might be as simple as including `yum` in our hidden imports list. I'll make a new build when I have time and see if that fixes it.

**Comment by basepi** [comment]
I've tracked it down to something related to pyinstaller. `pkg.version` works if you do a `python setup.py install` for hubble instead.

**Comment by basepi** [comment]
The wonderful @fossam has helped me track this down to a shared library issue. Basically, when rpm is called under hubble, it uses the rpmlib shared libraries that ship with hubble. This is why it works when you execute the commands outside of hubble, and why it works when you just do a python install.

@anuragpaliwal80 Can you try deleting the shared libraries and see if it fixes things (command below)? If so, I'll figure out a solution in my packaging, either leaving out those shared libraries or building directly on amazon linux.

```
rm /opt/hubble/hubble-libs/librpm*
```

**Comment by anuragpaliwal80** [comment]
Oh yes, it working now. Thanks

**Comment by basepi** [comment]
Perfect. Leaving this open until I automate the removal of those shared libraries in the package building stages.
