### ISSUE TITLE
Pulsar Masks not Working Windows 10

### ISSUE THREAD

**Issue by SpiritualMadMan** [hubblestack/hubble#656]
Hubble 2.4.7 Pulsar is work and the Folder Exceptions seem to be working as well.

However, nothing I do in masks seems to make a difference. I get the Create File event. But, Renaming and Deletes in my folder do not appear.

Running from C:\svr\hubble\... So, we aren't getting files from the repository. And, there are no errors in the log.

Using local returner sqlite

**Comment by basepi** [comment]
Can you show us your pulsar config? And the mask file you're using?

**Comment by SpiritualMadMan** [comment]
Basically I created a svr folder in my C: root and copied everything down to that.
C:\srv\hubble\hubblestack_pulsar
[hubble.conf.txt](https://github.com/hubblestack/hubble/files/3306617/hubble.conf.txt)
[hubblestack_pulsar_win_config.yaml.txt](https://github.com/hubblestack/hubble/files/3306627/hubblestack_pulsar_win_config.yaml.txt)

Is this what you needed?

My understanding of using the masks is that if you don't add a mask everything is captured.

I've actually tried it both way, with the same results.

Interesting that the exclude works, but the masks didn't...

**Comment by basepi** [comment]
I'm worried that maybe we have a case problem here. Note that when we do the comparison, it's case sensitive: https://github.com/hubblestack/hubble/blob/c0c0598864c9ca183fed2d61ff0e6baa3aedf35c/hubblestack/extmods/modules/win_pulsar.py#L339

But I'm seeing mismatches between the configured [DEFAULT_MASK](https://github.com/hubblestack/hubble/blob/c0c0598864c9ca183fed2d61ff0e6baa3aedf35c/hubblestack/extmods/modules/win_pulsar.py#L23) and the [documentation](https://github.com/hubblestack/hubble/blob/c0c0598864c9ca183fed2d61ff0e6baa3aedf35c/hubblestack/extmods/modules/win_pulsar.py#L66-L97)

Would you mind trying changing your mask to match that documentation (for upper/lowercase) and see if you can get it to have any effect?

**Comment by SpiritualMadMan** [comment]
I usually use (C#) ToUpper() if the case doesn't matter when doing a compare... 
Especially when the user can get it wrong. :)
I will look at how the NTFS Journal is read and see if I can make heads or tails out of it...

There's got to be more people out there doing this in Windows!

**Comment by SpiritualMadMan** [comment]
Ran a test as follows:
Started the Hubble Service
Created Text File
Renamed another file
Renamed a second file
Deleted File 
Deleted another File
Created a text File
Waited for the second data set to be posted.
Ran fsutil usn readjournal C: startusn=24887110816 > "C:\...
Collected the two data sets from the sqLite file.
The datasets are in Griddata.txt
The Journal data is in journal.txt

There is a gap in the Pulsar (grid data) at line 47 showing a gap that comes and goes.

Discoveries:
The Default Mask matches the journal data.
The renaming appears in the Journal data but not in the Pulsar data.

Suspect the ‘:’ in the Rename: is causing a problem with decoding/parsing the captured journal file.

My lead sat down and confirmed where the problem was and is offering a patch file, included. With the caveat that all we tried with it was to make Rename: old or new work.

If you don’t care whether you are dealing with a old name or new name just add Rename to the mask.

Hope this helps
[Grid_Data.txt](https://github.com/hubblestack/hubble/files/3307840/Grid_Data.txt)
[journal.txt](https://github.com/hubblestack/hubble/files/3307841/journal.txt)
[possible_fix.patch.txt](https://github.com/hubblestack/hubble/files/3307842/possible_fix.patch.txt)

**Comment by basepi** [comment]
Good catch! That does look like the culprit. I tweaked your provided patch to make it a little more succinct, here: https://github.com/hubblestack/hubble/pull/659

(I just limited the split to a single split, which should have the same effect.)

Thank you for figuring this out!
