### ISSUE TITLE
Ubuntu CIS profile 1604 error?

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#67]
_From @basepi on July 17, 2017 16:35_

_From @redonkuless on July 13, 2017 20:42_

Line: 629 I believe should read, 

 - net.ipv4.icmp_echo_ignore_bogus_error_responses:

instead of:

- icmp_echo_ignore_bogus_error_responses:

_Copied from original issue: hubblestack/hubble#64_

_Copied from original issue: hubblestack/hubblestack_data#32_

**Comment by basepi** [comment]
Thanks for the report, @redonkuless! Any chance you could submit a PR fixing this? Otherwise we'll grab it when we get a chance.

**Comment by basepi** [comment]
_From @redonkuless on July 17, 2017 17:39_

No idea how to do that. New to this.


________________________________

**Comment by basepi** [comment]
No worries, I'll get this fixed a little later today.

**Comment by basepi** [comment]
(Sorry for all the moves, I've been re-evaluating my issue management today and am moving everything into hubblestack/hubble. Which is where it was originally. My bad.)

**Comment by anuragpaliwal80** [comment]
I can take this.

**Comment by anuragpaliwal80** [comment]
Done with https://github.com/hubblestack/hubblestack_data/pull/34
