### ISSUE TITLE
rhels-6-level-1-scored-v2-0-1.yaml: 5.2.5 should support values less than 4

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#82]
_From @basepi on March 7, 2017 22:52_

_From @fdamstra on August 9, 2016 15:45_

CIS-5.2.5 requires the exact match of "MaxAuthTries 4". It should support any value <= 4. 

Other CIS modules should be checked as well.

_Copied from original issue: hubblestack/nova#226_

_Copied from original issue: hubblestack/hubble-salt#40_

**Comment by whackyhack** [comment]
This is cross-board.  centos-6, centos-7 has the same problem.

**Comment by basepi** [comment]
👍 thanks for the clarification. There's a fair amount of copy pasta, I think.

**Comment by whackyhack** [comment]
Pull request #49 added.  This bug is more dangerous than suggested in the title because it also produces false negatives, e.g., if MaxAuthRetries is set to 40 or 4000, it will show as compliant.

**Comment by basepi** [comment]
It'll be an awesome fix. Thanks for working to rebase your changes and clean up those PRs. 👍

**Comment by basepi** [comment]
Forgot to close this based on @whackyhack's work.
