### ISSUE TITLE
rhels-6-level-1-scored-v2-0-1.yaml: CIS-5.2.11 Requires unnecessary whitespace

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#84]
_From @basepi on March 7, 2017 22:52_

_From @fdamstra on August 9, 2016 15:50_

The module rule for CIS-5.2.11 requires that the 'Ciphers' line in sshd_config have trailing whitespace. This causes false positives on valid configurations that end the line after the third cipher.

This should match EOL ($) instead, or in addition.

Other CIS modules should be checked, as well.

_Copied from original issue: hubblestack/nova#228_

_Copied from original issue: hubblestack/hubble-salt#42_

**Comment by whackyhack** [comment]
This must have been fixed some while ago.  The following would have uncovered any trailing white space before $.
`
$ sed -n /sshd_approved_cipher/,/description/p *.yaml |fgrep ' $'
`

**Comment by basepi** [comment]
You're right, thanks for checking this.
