### ISSUE TITLE
Create "or" mechanism for grep module

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#85]
_From @basepi on March 7, 2017 22:53_

_From @basepi on September 28, 2016 19:23_

See the review comments on https://github.com/HubbleStack/Nova/pull/260 for examples. We either need to fix those examples with new `misc.py` checks, or allow for OR-ing in grep.py.

_Copied from original issue: hubblestack/nova#263_

_Copied from original issue: hubblestack/hubble-salt#43_

**Comment by basepi** [comment]
We've partially solved this by just using very large regular expressions in our grep commands, but it would still be nice to have `or` capability to keep the regex simpler.

**Comment by basepi** [comment]
https://github.com/hubblestack/hubble/blob/develop/hubblestack/files/hubblestack_nova/grep.py is the file in question. I have not thought this through all the way, so I'm unsure whether this will need to be a new module (grep_or.py) or if we can fit it into the existing data structure. Whatever changes we make to the existing data structure to allow for `or` need to be backwards compatible with the old format, so if we can't find a good way we can create a new module.

**Comment by mew1033** [comment]
I know @fossam talked about creating an awk module in addition to the current grep module. Awk would allow us to do 'or' matching pretty easily.

**Comment by basepi** [comment]
I think we're going to go with https://github.com/hubblestack/hubble/issues/109 instead of this one. I'll tell @rashmip29
