### ISSUE TITLE
Firewall Rule Audits

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#87]
_From @basepi on March 7, 2017 22:55_

_From @grimamethyst on May 5, 2016 3:6_

As part of PCI compliance, regular reviews of all prod firewalls are required.  However, this usually involves spending time going through the entire config file for each firewall.  That format is also generally impossible to hand off to auditors without copying out each individual rule from the config file.  Could the firewall tool built into Hubble include a feature that would pull in the rules and output them in a more organized, readable fashion?

_Copied from original issue: hubblestack/nova#118_

_Copied from original issue: hubblestack/hubble-salt#50_

**Comment by basepi** [comment]
I think this is doable, but will be low on the priority list for now.

**Comment by basepi** [comment]
I know this was originally a nova module, but since it's primarily information-gathering, I think this should actually be a new nebula module, as the labels infer. Nova is about auditing against standards, nebula is about information gathering.

**Comment by basepi** [comment]
Also, iptables is the only firewall we'll support for now.

**Comment by mew1033** [comment]
Not sure if it helps, but we're currently gathering iptables rules via osquery: https://github.com/hubblestack/hubblestack_data/blob/develop/hubblestack_nebula/hubblestack_nebula_queries.yaml#L38-L39

**Comment by basepi** [comment]
Interesting, I should have checked the query list. @grimamethyst would that serve your purposes? Sounds like we have this pretty handled at Adobe.

**Comment by basepi** [comment]
I'm going to close this, but if this doesn't serve your purposes please comment and we'll get it re-opened!
