### ISSUE TITLE
rhels-7-level-1-scored-v1.yaml requires both rsyslog and syslog-ng to be installed

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#90]
_From @lilmansplace on May 19, 2017 17:43_

salt-call hubble.top
....
Failure:
        |_
          ----------
          CIS-4.2.3:
              Ensure rsyslog or syslog-ng is installed
....
yet when I run:
rpm -qa | grep syslog
rsyslog-7.4.7-16.el7.x86_64

Once i've installed syslog-ng
rpm -qa | grep syslog
rsyslog-7.4.7-16.el7.x86_64
syslog-ng-libdbi-3.5.6-3.el7.x86_64

Both are now installed and the Failure is now a success
salt-call hubble.top
....
Success:
        |_
          ----------
          CIS-4.2.3:
              Ensure rsyslog or syslog-ng is installed

I don't think the point was that you need twice the log forwarders to be compliant.  Can this or become and actual or not an and.

Thanks!

_Copied from original issue: hubblestack/hubble-salt#71_

**Comment by basepi** [comment]
We definitely need to make this an `or`. Thanks for the report!

**Comment by whackyhack** [comment]
CIS' entire "Configure Logging" section (4.2 in CentOS 7 v2) is a mess.  This one is just the tip of the iceberg that has an easier fix.  Even though 4.2.3 says "Ensure rsyslog or syslog-ng is installed (Scored)", every other bullet under 4.2 goes with either rsyslog stuff or syslog-ng stuff.  A laundry list audit will give many false positives - nearly always 50%.

To really solve this problem, we need a conditional scan to check whether one of rsyslog and syslog-ng is installed, then branch accordingly.  Alternatively, we can use a conditional report to check that condition, then report accordingly.  In addition, an "N/A" kind of result is necessary to deal with CIS' incoherence.

Given that 4.2 sub-bullets are audited in 3 different modules, it could be easier to handle on the reporting side.  Either way, it requires heavy wiring between modules.

**Comment by basepi** [comment]
You are indeed right. Frustrating, we may have to do some pretty big architectural changes to get those right.

Or, more probably, we'll just write a misc.py check for them that can wire it all together with python.

**Comment by basepi** [comment]
I think this may have been fixed in all of our misc.py additions over the last year. Since this issue hasn't seen any movement I'm going to close it. If it should remain open please comment and I'll reopen.
