### ISSUE TITLE
Add ability to jsonify certain fields in osquery results

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#98]
Some results from osqueryi have json data underneath. Basically, we're going to prefix the *values* for these results with `__JSONIFY__`. So the splunk returner will iterate through the results and look for that prefix, and chop of that prefix and run the data through json before sending to splunk.

**Comment by basepi** [comment]
https://jira.corp.adobe.com/browse/CSTTEAM-41397

**Comment by fossam** [comment]
Just as a note, I tested against these changes with
`... | eval oooo=mvzip('environment{}.variable_name', 'environment{}.value', "=" ) | mvexpand oooo  | table _time, process_id, oooo` and the output was one environment variable=value per line, as expected.
